name: Windows-Qt5.15.2
on: 
  push:
    paths:
      - '*.sln'
      - '*.txt'
      - '*.bat'
      - '*.sh'
      - '3rdparty/**'
      - 'code/**'
      - 'config/**'
      - 'FluControls/**'
      - 'FluExamples/**'
      - 'FluIconTool/**'
      - 'FluUtils/**'
      - 'FluWinGallery/**'
      - 'res/**'
      - 'StyleSheet/**'
      - '.github/workflows/Windows-Qt5.12.2.yml'
  pull_request:
    paths:
      - '*.sln'
      - '*.txt'
      - '*.bat'
      - '*.sh'
      - '3rdparty/**'
      - 'code/**'
      - 'config/**'
      - 'FluControls/**'
      - 'FluExamples/**'
      - 'FluIconTool/**'
      - 'FluUtils/**'
      - 'FluWinGallery/**'
      - 'res/**'
      - 'StyleSheet/**'
      - '.github/workflows/Windows-Qt5.12.2.yml'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        include:
          - qt_ver: 5.15.2        
            qt_arch: win32_msvc2019
            msvc_arch: x86
            qt_arch_install: msvc2019          
    env:
      targetName: FluWinGallery.exe
      fileName: FluWinGallery
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.10.2
          
      - name: Install qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          cache: ${{steps.cache-qt.outputs.cache-hit}}
          
      - name: Msvc build & Package
        id: build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.msvc_arch }}
          mkdir build
          cd build
          cmake -DCMAKE_MESSAGE_LOG_LEVEL=STATUS -DCMAKE_PREFIX_PATH=D:\a\FluentUI\Qt\${{ matrix.qt_ver }}\msvc2019 -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -DCMAKE_BUILD_TYPE=Release -GNinja ..
          cmake --build . --target all --config Release --parallel
          echo winSdkDir=%WindowsSdkDir% >> %GITHUB_ENV%
          echo winSdkVer=%WindowsSdkVersion% >> %GITHUB_ENV%
          echo vcToolsInstallDir=%VCToolsInstallDir% >> %GITHUB_ENV%
          echo vcToolsRedistDir=%VCToolsRedistDir% >> %GITHUB_ENV%
          
      - name: New Release 
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/FluGalleryWin64Msvc.zip
          asset_name: ${{ env.fileName }}_${{ github.ref_name }}_${{ matrix.qt_arch }}_Qt${{ matrix.qt_ver }}.zip
          tag: ${{ github.ref }}
          overwrite: true
